title: "sdmeyers @github"
description: "&#x21DD; geeky fun techno babble..."
email: sdmeyers@gmail.com
guthub_username: sdmeyers

permalink: /blog/:year-:month/:title.html

# pagination

paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: "<!--more-->"
