baseURL = 'https://sdmeyers.github.io/'
languageCode = 'en-us'
title = 'sdmeyers@github'
[params]
    subtitle = '&#x21DD; geeky fun techno babble...'
theme = 'sdm-ghp'
[caches]
    [caches.images]
        dir = ':cacheDir/images'
